<?php
/**
 * Empire Safe — Production Queue
 * Shared helpers for the save/list/load endpoints.
 *
 * HTTP Basic Auth is enforced by the site-root .htaccess (Require valid-user),
 * so these scripts never see or manage credentials themselves.
 *
 * Directly requesting this file does nothing (it only defines functions) and is
 * behind Basic Auth regardless.
 */

// ---- Configuration ---------------------------------------------------------

/**
 * Hard cap on an incoming request body. Payloads include base64 photos, so this
 * is generous. It is deliberately set BELOW the recommended php.ini
 * post_max_size (see DEPLOY.md — recommended 25M) so that this script can
 * return a clean HTTP 413 before PHP itself silently discards an oversized body.
 */
const MAX_REQUEST_BYTES = 20 * 1024 * 1024; // 20 MB

// ---- JSON response ---------------------------------------------------------

/** Send a JSON response and end the request. */
function send_json($status_code, array $body): void {
    http_response_code($status_code);
    header('Content-Type: application/json; charset=utf-8');
    header('Cache-Control: no-store');
    // Defensive: this data is same-origin only; no cross-origin sharing.
    echo json_encode($body, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    exit;
}

// ---- Records directory -----------------------------------------------------

/** Absolute path to the records directory (a sibling of /api). */
function records_dir(): string {
    return dirname(__DIR__) . DIRECTORY_SEPARATOR . 'records';
}

/**
 * Contents of the deny-all .htaccess that must live inside the records dir.
 * save.php re-writes this if the directory is created at runtime, so the
 * lockdown exists even on a freshly created (FTP-less) records directory.
 */
function records_htaccess_body(): string {
    return "# Auto-generated by save.php. Deny all direct web access to records.\n"
         . "Require all denied\n"
         . "<IfModule !mod_authz_core.c>\n"
         . "  Order allow,deny\n"
         . "  Deny from all\n"
         . "</IfModule>\n";
}

/**
 * Ensure the records directory exists, is writable, and is locked down.
 * Returns [true, path] on success or [false, errorMessage] on failure.
 *
 * FTP-created directories are often owned by a different user than the one PHP
 * runs as, so we do not assume write access — we create and verify it here.
 */
function ensure_records_dir() {
    $dir = records_dir();

    if (!is_dir($dir)) {
        // Suppress the warning; we report the failure as JSON ourselves.
        if (!@mkdir($dir, 0775, true) && !is_dir($dir)) {
            return [false, 'Could not create the records directory on the server. '
                . 'Create a "records" folder next to the api folder via FTP and make it writable.'];
        }
    }

    if (!is_writable($dir)) {
        return [false, 'The records directory exists but is not writable by the web server. '
            . 'Set its permissions to 0775 (or 0777 on strict hosts) via FTP so PHP can write to it.'];
    }

    // Make sure the deny-all lock is present (defense in depth).
    $htaccess = $dir . DIRECTORY_SEPARATOR . '.htaccess';
    if (!file_exists($htaccess)) {
        @file_put_contents($htaccess, records_htaccess_body());
    }

    return [true, $dir];
}

// ---- Filename safety -------------------------------------------------------

/**
 * Sanitize a record filename independently of anything the client sent.
 * Strips everything outside [A-Za-z0-9._-], forbids traversal, and requires a
 * .json extension. Returns the safe basename, or null if it cannot be trusted.
 */
function sanitize_record_filename(?string $name): ?string {
    if ($name === null) return null;

    // Never trust a path — only ever a basename.
    $name = basename($name);

    // Reject anything with traversal or separators that survived basename().
    if ($name === '' || strpos($name, '..') !== false
        || strpos($name, '/') !== false || strpos($name, '\\') !== false) {
        return null;
    }

    // Strip to the safe character set.
    $name = preg_replace('/[^A-Za-z0-9._-]/', '', $name);
    if ($name === '' || $name[0] === '.') return null;

    // Must be a .json file.
    if (!preg_match('/\.json$/i', $name)) return null;

    return $name;
}

/**
 * Resolve a safe basename to an absolute path and confirm it really sits inside
 * the records directory (belt-and-suspenders against path traversal).
 * Returns the absolute path, or null if it would escape the directory.
 */
function resolve_inside_records(string $safeBasename): ?string {
    $dir = records_dir();
    $target = $dir . DIRECTORY_SEPARATOR . $safeBasename;

    // The parent (records dir) must resolve; the file itself may not exist yet.
    $realDir = realpath($dir);
    if ($realDir === false) return null;

    $realTarget = realpath($target);
    if ($realTarget !== false) {
        // Existing file: it must be within the records dir.
        if (strpos($realTarget, $realDir . DIRECTORY_SEPARATOR) !== 0) return null;
        return $realTarget;
    }

    // New file: validate the intended path string stays under the records dir.
    $intended = $realDir . DIRECTORY_SEPARATOR . $safeBasename;
    if (strpos($intended, $realDir . DIRECTORY_SEPARATOR) !== 0) return null;
    return $intended;
}

/**
 * Build the SO-based base name (without extension or _vN suffix) from the
 * client's sales-order value, sanitized server-side. Falls back to a
 * timestamped NOSO name when no sales order was entered.
 */
function so_base_name(?string $soNum): string {
    $clean = preg_replace('/[^A-Za-z0-9]/', '', (string)$soNum);
    if ($clean === '') {
        return 'NOSO_' . date('Ymd_His');
    }
    // Avoid producing "SOSO123" if the user already typed "SO123".
    if (preg_match('/^so/i', $clean)) {
        return strtoupper(substr($clean, 0, 2)) . substr($clean, 2);
    }
    return 'SO' . $clean;
}
